name: Build and Push to repository

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

jobs:
  build:
    runs-on: docker
    container:
      image: git.fran.cam/homelab/runner:latest@sha256:48a56e5517282e23af3d90498ba658d883a96e53e37fb742bf1e4ec4b1c37927
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build runner image
        run: |
          docker build -t git.fran.cam/homelab/filebrowser:latest .

      - name: Login to registry
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.BOT_PASSWORD }}" | docker login git.fran.cam -u "bot@fran.cam" --password-stdin

      - name: Push runner image
        if: github.event_name == 'push'
        run: |
          docker push git.fran.cam/homelab/filebrowser:latest
