name: Build and Push to repository

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sundays

jobs:
  build:
    runs-on: docker
    container:
      image: hub.fran.cam/runner:latest@sha256:233244a2d8c27f35c173911bc5b484f03050eebd83f59ae11429e8635d41ca2a
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build runner image
        run: |
          docker build -t git.fran.cam/homelab/filebrowser:latest .

      - name: Login to registry
        if: github.event_name == 'push'
        run: |
          echo "${{ secrets.BOT_PASSWORD }}" | docker login git.fran.cam -u "bot@fran.cam" --password-stdin

      - name: Push runner image
        if: github.event_name == 'push'
        run: |
          docker push git.fran.cam/homelab/filebrowser:latest
